name: Update Readme

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  update:
    name: Update repo README
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
        
    - uses: gautamkrishnar/blog-post-workflow@1.6.1
      with:
        comment_tag_name: "BLOG-POSTS"
        feed_list: "https://www.aspitalia.com/my/feed.aspx?k=akXGpKy7IvI%3d"

    - uses: Readme-Workflows/recent-activity@v2.3.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
