name: Update Readme

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  update:
    name: Update repo README
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
        
    - uses: gautamkrishnar/blog-post-workflow@master
      with:
        comment_tag_name: "BLOG-POSTS"
        feed_list: "https://www.aspitalia.com/my/feed.aspx?k=akXGpKy7IvI%3d"

    #- name: Add activity to readme
    #  uses: Readme-Workflows/recent-activity@main
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #  with:
    #    CONFIG_FILE: "recent-activity.config.yml"
